### PR TITLE
Change Dark prismarine to use black dye.

### PR DESCRIPTION
**Pull request by RedDevel2**
Just changing the Dark prismarine recipe to use black dye instead of inc sacs to make it consistent with other "dyeing" recipes.

### CODE REVIEW

**Comment by AngrySoundTech** [comment]
As far as I'm aware the only other recipe that uses dye is purpur (outside of the literal "Dye terracotta" recipes), which is an end block so doesn't immediately have anything analogous. I kind of like prismarine needing sea items to make, but that's also just my immediate opinion. I'd be interested to see what others think.

**Comment by RedDevel2** [comment]
You technically still are since black dye is almost exclusively made with inc sacs. But it's just more handy for the recipe to have black dye than raw inc since there's no way to turn the dye back into inc. Which would mean having to go out and kill more squids, an annoying task for some pretty blocks. especially when you've got a bunch of dye around already. Basically a quality of life change.
Just my reasoning there.

**Comment by RedDevel2** [comment]
I've seen many people complain now about the lack of squids primarily because they need ink for dark prismarine. since upping the amount of squids is not really an option, I feel this small change would make sense.

**Comment by wingzero54** [comment]
I'm fine with this, not really something I think is worth fighting a lot over. Especially since vanilla Minecraft allows crafting dark prismarine with black dye as well. I'll merge unless there's any objections

**Comment by RedDevel2** [comment]
#183

**Pull request closed without merging**
