### PR TITLE
Gravel Production

### PR DESCRIPTION
**Pull request by Yergos**
Add gravel production from cobbled deepslate to the aesthetics factory.

### CODE REVIEW

**Comment by Protonull** [comment]
Personally, I am very much against this change... why do we need to create an absolute abundance of every single material? To make concrete cheaper? Why should the admins interfere in this way to make concrete cheaper? Gravel is already in abundance, you just need to mine it... is that so hard?

**Comment by Yergos** [comment]
> Personally, I am very much against this change... why do we need to create an absolute abundance of every single material? To make concrete cheaper? Why should the admins interfere in this way to make concrete cheaper? Gravel is already in abundance, you just need to mine it... is that so hard?

Gravel is a very difficult material to collect in the quantity that players who _do_ use gravel use it in. Gravel was previously a very abundant material due to the existence of the grinding factory, and this did not cause balance issues of any kind (unlike the sand grinding recipe, which is removed for understandable reasons). The relatively scarcity is a shock for those of us who previously utilized it in projects such as overland rail construction and makes it difficult for some to play without spending hours diving in the ocean or scouring caves to collect gravel deposits. Many of these people (myself included) simply do not have the ability to dedicate that much time to CivCraft due to real-life obligations, and would prefer to spend the limited time we do have in the game doing the things that actually motivate us to log in, rather than mind-numbing grinding. I understand the reasoning behind requiring players to grind out certain resources (such as those used in vault construction), but this is not one of those resources that needs to be scarce.

**Comment by CaptainKlutz** [comment]
Completely unnecessary change. Gravel is extremely plentiful on the ocean floor, which you can mine on using silk shovels and aqaff helmets from the gold forge. I don't know if you played on Devoted 2.0 but the config for aesthetics materials on that iteration had a wanton abundancy of every material; the result was there was no value or uniqueness assigned to different materials, and every city looked the same and was unimpressive due to lack of effort needed to get materials. I, too, have limited free time, but I work around it and understand that sometimes things will take longer to acquire and build than I want.

**Comment by Protonull** [comment]
> This is not a desired change, one of the goals of the current server balance is forcing players to either trade or mine at different levels to acquire the resources they need. Making deepslate a reinforcement would make it drastically easier to never need to mine at different levels, and also make it easier to gather the resources needed for a build while digging the hole it occupies, something else we wanted to limit.
>
> \- Wingzero, #30

Just because we have an abundance of a material doesn't mean it should warrant admin intervention. Your hoarding of deepslate is not a problem that the admins need to solve :P

**Comment by adeadhead** [comment]
Just here to chime in that gravel is renewable via piglin trading.

**Comment by adeadhead** [comment]
Just because portal farms are possible doesn't mean gold farms aren't.

**Comment by Protonull** [comment]
Hmmm, even assuming that gold farms exist and produce massive amounts of gold, given that Piglin trading is a vanilla feature and that gravel has such a low trade-rate, it's not worth fussing about. Dirt is artificially far, *far* more renewable than gravel. I think the main difference here is that this PR attempted admin intervention specifically to make gravel plentiful... whereas someone creating a massive gold farm and spamming trades with Piglins is simply using features already in the game. The question then becomes, if Piglin trading is too OP, should the admins intervene to disable or adjust it? And if it ever got to that discussion, it probably wouldn't be over gravel.

If gold farms are possible then I humbly suggest @Yergos to take advantage of Piglin trading for gravel.

**Pull request closed without merging**
