### PR TITLE
Add help message with information on how to join global chat

### PR DESCRIPTION
**Pull request by grepsedawk**
Currently, there is a confusing message that instructs users to type
/g ! in order to "join" global chat, which doesn't work if the user
isn't already in the global group

Instead, add a new message to tell users how to join (and leave!) global
chat, and change the existing messaging to better communicate what /g !
does when executed

### CODE REVIEW

**Comment by wingzero54** [comment]
It's because players are supposed to be getting invited automatically via Kira, but Kira is not working well so that isn't happening

**Comment by grepsedawk** [comment]
Would you like me to close this?
It still seems like a useful addition in the meantime

**Comment by wingzero54** [comment]
> Would you like me to close this? It still seems like a useful addition in the meantime

We need to confirm if this is still an issue, most of the Kira functionality appears to be restored with the update to KiraBukkitGateway

**Comment by wingzero54** [comment]
Actually it's fine, this is a good change either way. Thanks greps

**Review by wingzero54 — COMMENTED** [review]
lgtm

**Pull request merged**
