### PR TITLE
Add signs to "permeable" blocks for Item Exchange relays

### PR DESCRIPTION
**Pull request by MrJeremyFisher**

### CODE REVIEW

**Comment by wingzero54** [comment]
Can you give some reasoning for this request?

**Comment by Protonull** [comment]
Even if you want to do this, you'd want to add the wall-sign equivalents too.

**Comment by MrJeremyFisher** [comment]
> Even if you want to do this, you'd want to add the wall-sign equivalents too.

Ah, might be better to do some rewriting to switch to allowing any transparent and blacklisting then



> Can you give some reasoning for this request?

Signs are counted as transparent in other areas, it makes sense that exchanges should be able to pass through them. Visually they don't even block the "signal" in the same way glass might be expected to, as they do not cover the chest.

**Comment by wingzero54** [comment]
I'm opposed as this is against the spirit of the permeable blocks for shop relays, and signs wouldn't help protect a shop like glass or iron bars do

**Comment by MrJeremyFisher** [comment]
Signs are non-solid though. They don't protect chests but they do block relays in unexpected ways given that the game treats them as transparent in every other situation. As it stands, this is an inconsistency in how transparent blocks are handled. See the attached screenshots for more context as to how this is a) unintuitive and b) inconsistent with other behaviour. Both situations depicted are essentially the same, a non-full block between a relay, yet one works and the other doesn't.
image
image

**Comment by Protonull** [comment]
> I'm opposed as this is against the spirit of the permeable blocks for shop relays, and signs wouldn't help protect a shop like glass or iron bars do

Yeah, tbh, the notion that any permeable block MUST add protection kinda implies that the AIR block types should be removed.

**Comment by wingzero54** [comment]
Not a desired change for the server, doesn't fit with the intentions of shop relays

**Pull request closed without merging**
