### PR TITLE
Add the joke paper reinforcement from CivClassic instead of deepslate 

### PR DESCRIPTION
**Pull request by nebula161**

### CODE REVIEW

**Comment by AngrySoundTech** [comment]
The paper reinforcement from classic wasn't a joke, it was a donator reinforcement.


That being said, I do like how people used it at christmas to "wrap" gifts to each other :)

**Comment by nebula161** [comment]
> The paper reinforcement from classic wasn't a joke, it was a donator reinforcement.
I'm aware, I just called it that because all of the stats were 1

**Comment by Protonull** [comment]
> The paper reinforcement from classic wasn't a joke, it was a donator reinforcement.

*Two things can be true at once.*

**Comment by adeadhead** [comment]
I'm not saying I'm against it, but a 1 strength reinforcement needs to have acid block functionality disabled, to prevent it being used to generate obsidian more easily and cheaply than current methods.

**Comment by Protonull** [comment]
How would a paper reinforcement make obsidian generation easier? Genuinely curious

**Comment by wjkroeker** [comment]
> How would a paper reinforcement make obsidian generation easier? Genuinely curious

Right now, you could make a line of obby with lava and water, /ctr it with stone, and then stone-reinforce acid blocks underneath. You can do as many blocks of obby at once as you have blocks of gold per "run" (20 minute maturation time on the acid), and each one will cost 1 stone (the other stone reinforcement you get back). 

With paper or a similarly cheap 1 strength reinforcement, you could do the same thing but presumably cheaper.

**Comment by Protonull** [comment]
That's some galaxy brained shit right there! I have to agree then that acid should be disabled it

**Comment by adeadhead** [comment]
> With paper or a similarly cheap 1 strength reinforcement, you could do the same thing but presumably cheaper.

The issue here is acid warmup is based on reinforcement strength, so it would have a 5 second or whatever warmup, and be bottable faster than you could mine the obsidian.

**Comment by RedDevel2** [comment]
Now that maturation times have increased, would adding paper reinforcement still mean that it would be faster to bot obsidian with it, than by mining it?

**Pull request closed without merging**
