### PR TITLE
Reset AutoRespawn quotes

### PR DESCRIPTION
**Pull request by Protonull**
Not sure why Max set it to "You wake up in an unfamiliar place..." since that's the random-spawn message and this isn't that.

### CODE REVIEW

**Comment by Maxopoly** [comment]
Because it was the original quote displayed when you respawned in Civcraft 2.0

**Comment by AngrySoundTech** [comment]
Neat, I didn't know we could add more. I'd like to keep the "You wake up in an unfamiliar place" though, and cut out the ones that don't make sense for a first time spawn though

**Comment by Protonull** [comment]
> cut out the ones that don't make sense for a first time spawn though

That's the thing though, this is an update to the AutoRespawn config, not the RandomSpawn config. AutoRespawn does nothing but forcibly respawn people after X amount of time being dead. The messages are just fun extras to indicate to the player that they've been respawned. Keep in mind that the reason why this PR is titled "**Reset** AutoRespawn quotes" is because this PR is resetting the config back to the [default config](https://github.com/CivMC/SimpleAdminHacks/commit/67e90ac89ba165c160be03766c94f7c9a5a3126b#diff-58cdd3d308ccba6c594e040ff9c065bb11eeb6e30f35ba87694ea45d5ae6096c). I was always a little perplexed that Maxopoly [enabled AutoRespawn](https://github.com/CivClassic/AnsibleSetup/commit/fc59758dc9f8c461620e06a04b17987c5b250ad5) with solely the RandomSpawn quote, which means you get the same message dying while afk and respawning in your house, as dying in PVP and getting random-spawned somewhere.

**Comment by wingzero54** [comment]
Is there any way for this to reference the method of death?  One big gripe players have is they will come back to the game and find they've been respawned and have no idea why or how it happened. I know that's out of the scope of the respawn message

**Comment by Protonull** [comment]
> Is there any way for this to reference the method of death? One big gripe players have is they will come back to the game and find they've been respawned and have no idea why or how it happened. I know that's out of the scope of the respawn message

Hmmm, it's bizarre... there's no easy way to gleam this information. It's not on [PlayerDeathEvent](https://jd.papermc.io/paper/1.18/org/bukkit/event/entity/PlayerDeathEvent.html) or its parent [EntityDeathEvent](https://jd.papermc.io/paper/1.18/org/bukkit/event/entity/EntityDeathEvent.html), nor is it on [PlayerRespawnEvent](https://jd.papermc.io/paper/1.18/org/bukkit/event/player/PlayerRespawnEvent.html) or [PlayerPostRespawnEvent](https://jd.papermc.io/paper/1.18/com/destroystokyo/paper/event/player/PlayerPostRespawnEvent.html). You could, perhaps, do some logic on the death message for PlayerDeathEvent but that's jaaaanky. Those closest to a solution is [Entity#getLastDamageCause()](https://jd.papermc.io/paper/1.18/org/bukkit/entity/Entity.html#getLastDamageCause()) immediately after a player has died and then caching the result somehow. I'm not sure if it'll work in all cases though... like does the `/kill` command work properly? Would it be recorded as "damage dealt" or.. I dunno, probably worth some testing.

**Comment by Protonull** [comment]
...but even then, you'd only get the "last hit" reason. Say you were pvp-ing but technically died to fall damage. Would it be more accurate to say they lost in pvp battle or succumb to environment damage?

**Comment by Protonull** [comment]
> One big gripe players have is they will come back to the game and find they've been respawned and have no idea why or how it happened.

I could change the messages to something like "You have been automatically respawned."

**Comment by AngrySoundTech** [comment]
I think in this case this is fine a fine PR, and we can plan some follow on work to address players not knowing what killed them. The contents of this PR do seem to address the intent of it and I don't see  any issues with it

**Review by AngrySoundTech — APPROVED** [review]

**Pull request closed without merging**
