### PR TITLE
Change BanStick to be built automatically instead of manually

### PR DESCRIPTION
**Pull request by griffinht**
This is an example of how the rest of the plugins may be
automatically built from source. This approach means plugins do not
need to be manually compiled, and the plugin jars do not need to be
checked in to version control.

Updating plugins can also be automated by bumping the version and
SHA256 hash to the newer version. It is important to check the
SHA256 hash in order to verify the integrity of the source code
matches the tag we are trying to build.

Unforutunately many of the plugins don't seem to provide binaries,
so we must build the plugin jar ourselves. This requires Maven
packages from the GitHub Package Repository which requires a valid
Personal Access Token with read:packages.

It would be even nicer if the upstream plugins could provide their
own compiled jars, and all CivDocker had to do was download the jar
from the plugin instead of downloading the plugin's source code and
building. This would also avoid having to provide a GitHub Personal
Access Token.

It would also be nice to make sure these builds are reproducible,
but that is something to think about later.
See https://reproducible-builds.org/ and
https://reproducible-builds.org/docs/jvm/

### CODE REVIEW

**Comment by griffinht** [comment]
This starts to address https://github.com/CivMC/CivDocker/issues/3

**Comment by Gjum** [comment]
All the download+check+etc. logic could be in a shell script COPYed at the beginning, and then called with one line for each jar. This also helps keeping it DRY without splitting downloading from copying to the final image. I don't think we need to cache the jars so we can just download them all during every build.

**Comment by griffinht** [comment]
Some code could be moved to a shell script, but it is important to make sure we take advantage of Docker's caching mechanism. Updating one plugin should not result in the rest of the plugins being updated. Updating each plugin currently involves downloading and building from the source code. This takes a long time and requires some build dependencies like Gradle. It is important to make sure this long process can be cached. Also, build dependencies should be kept out of the final stage so the image size remains low.

This approach seems complex and would involve a fair bit of code. It would be much more simple if the upstream plugins could provide the compiled binaries, and all we had to do here was download them.

@AngrySoundTech It seems like you maintain a lot of these upstream plugins. What do you think of providing the compiled jar with each release you publish? For example, if BanStick's [v2.0.0-SNAPSHOT-2 release](https://github.com/CivMC/BanStick/releases/tag/v2.0.0-SNAPSHOT-2) also provided a compiled jar as an asset, then all we would have to do here is download it.

**Comment by Gjum** [comment]
We're in agreement. The shell script would just bundle the 4-5 lines of download+check so it's not repeated for every plugin in the Dockerfile. Building each plugin in their own CI and then just downloading them all during this Docker build process is the way to go. I don't know enough about Github CI capabilities to tell whether we can just download+commit the jars into this repo when they're updated in the other repos' releases, to make better use of Docker caching.

**Comment by Gjum** [comment]
To publish each plugin, it seems we can just update this https://github.com/CivMC/.github/blob/master/.github/workflows/gradle_publish.yml#L29
to something like this: https://github.com/Gjum/SnitchMod/blob/master/.github/workflows/build.yml#L23

**Comment by griffinht** [comment]
The changes to you are proposing to https://github.com/Gjum/SnitchMod/blob/master/.github/workflows/build.yml#L23 is exactly what would be helpful to CivDocker. I believe it would require a maintainer to make these changes. 

Once this is done, my PR can be updated to download these compiled jars from each plugin in Docker.

**Comment by AngrySoundTech** [comment]
We don't want to build plugins from source in Docker, here, we will however be providing the built jars on the plugin releases after we have a non-snapshot version

**Pull request closed without merging**
