### PR TITLE
Add copper workshop

### PR DESCRIPTION
**Pull request by walkersgaming**
Add copper workshop factory with recipes to weather and wax copper blocks

### CODE REVIEW

**Comment by wingzero54** [comment]
This factory is a good addition, totally slipped by me. @walkersgaming can you update this for the current FM config? There's some conflicts from FM updates. 

As for balance/ cost, what do you think of 8 honeycomb for each stack? And increasing it to 4 water buckets for weathering

**Comment by RedDevel2** [comment]
Instead of 4 water, which might be annoying in bulk. We can change the fuel like we do for the bio factory to add a cost there.

**Comment by walkersgaming** [comment]
Probably didn't do it the exact right way, but caught up the PR with latest.

@RedDevel2 if this is about saving time (helping builders) doesn't it make sense to be fairly cheap? What do you suggest the fuel cost be instead?

**Comment by Solitaire7** [comment]
Does copper oxidisation actually need to be something that's added to a factory ? It's possible to make farms for oxidising copper in vanilla that use the catalysing ability of "older" copper along with the proximity to other copper blocks factor to speed up oxidisation quite a bit. I imagine with civ this could be taken even further with bots potentially drastically simplifying the designs for such farms that utilise these two factors effecting oxidisation speed. 

I've seen many other people successfully sell different building blocks, and I don't necessarily think making something that is potentially another niche industry for people to enter into just another easy factory recipe is the right approach to take. Builders are also a part of the world and should have to interact with it/with other players in some way. I think removing this potential niche just because currently no one has tried to make either a vanilla style catalysing oxidation farm, or a new more simple oxidation farm utilising bots that would be unique to CivMC is adding an easy fix for no reason that removes a potential unexplored niche. 

Even just spreading the copper blocks out into the optimal distance, without any catalysing blocks present, underneath an active area has allowed a lot of people to obtain vast amounts of oxidised copper for very large copper builds quite easily. This could be taken even further if someone wished to by actually designing a farm around both the distance factor and the catalyst factor that greatly decreases the time in which they can oxidise vast amounts of copper blocks.

In relation to the waxxing recipe, and being able to wax large amounts of copper through a factory I do think this is a good addition as it just replaces a very simple script, whereas oxidation farms would be more complex with either approach. However, I think the honeycomb discount is far too much as red said. Honeycomb is one of the easiest items to farm in very large quantities with even a very small farm from what I have seen. The current proposal here would give a discount of 0.9375 honeycomb per copper block. I think that realistically farms that make honeycomb produce so much that there's not really a reason to devalue it any further (it is already valued pretty low when you buy it) and that a waxxing factory should realistically just make it easy for people to wax large amounts quickly at the same cost as vanilla of 1 honeycomb per waxxed block.

Similarly to the waxxing recipes though you could add a stripping recipe, using iron axes maybe, that allows you to strip large number of copper in a similar fashion to the waxxing factory. As this again would replace a very simple script similarly to the waxxing recipe and in contrast to the different complex farm options you have for the initial oxidising stage. 
An iron axe has a durability of 250, so maybe 1 iron axe + 4 stacks of some sort of oxidised copper would revert those 4 stacks back to the stage directly before the one they are at and consume the axe.

**Comment by walkersgaming** [comment]
> Does copper oxidisation actually need to be something that's added to a factory ? It's possible to make farms for oxidising copper in vanilla that use the catalysing ability of "older" copper along with the proximity to other copper blocks factor to speed up oxidisation quite a bit. I imagine with civ this could be taken even further with bots potentially drastically simplifying the designs for such farms that utilise these two factors effecting oxidisation speed.
> 
> I've seen many other people successfully sell different building blocks, and I don't necessarily think making something that is potentially another niche industry for people to enter into just another easy factory recipe is the right approach to take. Builders are also a part of the world and should have to interact with it/with other players in some way. I think removing this potential niche just because currently no one has tried to make either a vanilla style catalysing oxidation farm, or a new more simple oxidation farm utilising bots that would be unique to CivMC is adding an easy fix for no reason that removes a potential unexplored niche.
> 
> Even just spreading the copper blocks out into the optimal distance, without any catalysing blocks present, underneath an active area has allowed a lot of people to obtain vast amounts of oxidised copper for very large copper builds quite easily. This could be taken even further if someone wished to by actually designing a farm around both the distance factor and the catalyst factor that greatly decreases the time in which they can oxidise vast amounts of copper blocks.
> 
> In relation to the waxxing recipe, and being able to wax large amounts of copper through a factory I do think this is a good addition as it just replaces a very simple script, whereas oxidation farms would be more complex with either approach. However, I think the honeycomb discount is far too much as red said. Honeycomb is one of the easiest items to farm in very large quantities with even a very small farm from what I have seen. The current proposal here would give a discount of 0.9375 honeycomb per copper block. I think that realistically farms that make honeycomb produce so much that there's not really a reason to devalue it any further (it is already valued pretty low when you buy it) and that a waxxing factory should realistically just make it easy for people to wax large amounts quickly at the same cost as vanilla of 1 honeycomb per waxxed block.
> 
> Similarly to the waxxing recipes though you could add a stripping recipe, using iron axes maybe, that allows you to strip large number of copper in a similar fashion to the waxxing factory. As this again would replace a very simple script similarly to the waxxing recipe and in contrast to the different complex farm options you have for the initial oxidising stage. An iron axe has a durability of 250, so maybe 1 iron axe + 4 stacks of some sort of oxidised copper would revert those 4 stacks back to the stage directly before the one they are at and consume the axe.

I doubt people bother with farms for oxidising given you can just place it and wait for it to oxidise. The point of factories is to add recipes to improve QOL, which this does. Enabling builders to expand the repertoire of blocks they can/want to build with

**Comment by Solitaire7** [comment]
> > Does copper oxidisation actually need to be something that's added to a factory ? It's possible to make farms for oxidising copper in vanilla that use the catalysing ability of "older" copper along with the proximity to other copper blocks factor to speed up oxidisation quite a bit. I imagine with civ this could be taken even further with bots potentially drastically simplifying the designs for such farms that utilise these two factors effecting oxidisation speed.
> > I've seen many other people successfully sell different building blocks, and I don't necessarily think making something that is potentially another niche industry for people to enter into just another easy factory recipe is the right approach to take. Builders are also a part of the world and should have to interact with it/with other players in some way. I think removing this potential niche just because currently no one has tried to make either a vanilla style catalysing oxidation farm, or a new more simple oxidation farm utilising bots that would be unique to CivMC is adding an easy fix for no reason that removes a potential unexplored niche.
> > Even just spreading the copper blocks out into the optimal distance, without any catalysing blocks present, underneath an active area has allowed a lot of people to obtain vast amounts of oxidised copper for very large copper builds quite easily. This could be taken even further if someone wished to by actually designing a farm around both the distance factor and the catalyst factor that greatly decreases the time in which they can oxidise vast amounts of copper blocks.
> > In relation to the waxxing recipe, and being able to wax large amounts of copper through a factory I do think this is a good addition as it just replaces a very simple script, whereas oxidation farms would be more complex with either approach. However, I think the honeycomb discount is far too much as red said. Honeycomb is one of the easiest items to farm in very large quantities with even a very small farm from what I have seen. The current proposal here would give a discount of 0.9375 honeycomb per copper block. I think that realistically farms that make honeycomb produce so much that there's not really a reason to devalue it any further (it is already valued pretty low when you buy it) and that a waxxing factory should realistically just make it easy for people to wax large amounts quickly at the same cost as vanilla of 1 honeycomb per waxxed block.
> > Similarly to the waxxing recipes though you could add a stripping recipe, using iron axes maybe, that allows you to strip large number of copper in a similar fashion to the waxxing factory. As this again would replace a very simple script similarly to the waxxing recipe and in contrast to the different complex farm options you have for the initial oxidising stage. An iron axe has a durability of 250, so maybe 1 iron axe + 4 stacks of some sort of oxidised copper would revert those 4 stacks back to the stage directly before the one they are at and consume the axe.
> 
> I doubt people bother with farms for oxidising given you can just place it and wait for it to oxidise. The point of factories is to add recipes to improve QOL, which this does. Enabling builders to expand the repertoire of blocks they can/want to build with

Factories shouldn't just replace existing farms, or manual collection, though which can very much exist to produce blocks where their main purpose is to build with them. I've seen people selling blocks such as terracotta which only exist to be built with, and there's no way to even improve the efficiency of collection and it relies on manual collection. Just because something is primarily built with doesn't mean that every aspect of it's production should be moved into factories. 

And copper blocks (of all weathering stages) very much currently exist within the repertoire of builders, people already gather large amounts of copper at different stages of weathering to build with it. The oxidising of the copper isn't even the most tedious aspect of collecting a large amount of partially oxidised copper, neither is it the second. By placing copper at the optimal distance underneath an active area it is very easy to oxidise a large amount of copper within  few days, considering builders use other blocks they can easily use these few days to gather other blocks or work on another building, this is how I oxidised 4-5 cs of copper blocks for a build. 

And this is only putting in the minimal amount of effort to speeding the process up, using catalysts, a bot, or redstone mechanics of some sort can all also speed up the process further. Many other "building" blocks are currently not made in factories but though farms, or just by manual collection, at least in their "primary" stage. Wool has to be made from string, or by killing or shearing sheep, dyes are collected from flower farms, or other resources, plain terracotta is mined, honeycomb is mass produced via honeycomb farms etc... All of these give new niches for players to work in and produce goods to sell, the oxidisation process of aging copper would very much belong to a similar style of farming and of producing the "primary" stage of oxidation.

The much more tedious parts of producing the 2nd and 3rd stages of oxidation specifically in very large quantities, from my person experience, are the waxxing stage and also the stripping stage (which isn't even mentioned here). If the true aim is to help builders and to make the production process easier then these are the two stages which should actually be moved to factories. 

The stripping stage is likely the most tedious stage as for every single fully oxidised copper block you have to right click it once or twice with an axe (consuming durability) and then mine it. The waxxing is also somewhat tedious but less so, as you can wax up to 64 blocks at once. These are the two processes which should be moved to a factory. The actual initial oxidation of the copper is fine as it is, even just leaving it under an active area in the optimal spacing allows you to oxidise large amounts of copper within 3 hours (you don't have to be there, the area is active so anyone else in the area is also loading it while you are off doing something else) and it can be sped up further using catalysing blocks, which you could then use redstone mechanics or bots alongside but it's not even necessary tbh as you just leave it in the active area and then come back later and mine it.

**Comment by Protonull** [comment]
While I tend to agree with the kind of argument @Solitaire7 is making here, copper is so ridiculously abundant that it really doesn't matter. You could mistakenly let an entire "farm" oxidise too much and little of value would be lost. For that reason, I think reducing the overall tedium of it all seems like a good idea.

**Comment by walkersgaming** [comment]
@wingzero54 @RedDevel2 let me know if you have further thoughts on costs/fuel

**Comment by RedDevel2** [comment]
I think:
64 copper blocks, 32 wax for waxing recipe
64 copper blocks 1 water bucket for ageing recipe.
With the fuel being amethyst crystals, since it's the closest thing to a mineral that could oxidize, and is decently abundant.
And then make each step of aging take longer, and thus use more fuel the higher in age you want your copper to be.

**Comment by Solitaire7** [comment]
That's pretty interesting, I like that it does introduce a use for amethyst crystals. What would your thoughts be on adding a scraping recipe similar to waxxing ? It's a more tedious process than waxxing as you have to go block by block whereas waxxing you can do a stack at a time in a crafting grid.

A potential recipe (since scraping takes axe durability) could be 4 stacks copper blocks + 1 iron axe returns 4 stacks copper blocks at the oxidation stage directly before (so you'd need 4 recipes similar to waxxing). And 1 diamond axe would scrape 24 stacks.

You could also potentially have 2 separate versions of the recipe 1 using iron axes and 1 using diamond axes, and then have the fuel be emeralds and allow the consumption of the singular iron/diamond axe to scrape a number of stacks similar to their durability with unbreaking 3. So for the iron axe recipe that'd be 16 stacks and for a diamond axe it'd be 96 stacks if you go by the vanilla durability. But maybe since these are bulk recipes they could be in an upgraded version of the factory (or just have greater efficiency anyway) and the iron axe + emeralds recipe could scrape 20 stacks and the diamond axe + emeralds recipe could scrape 2 ci. This would give a way to reduce the iron/diamond cost in return for supply emeralds, similar to how you can scrape more copper blocks with an unbreaking 3 axe.

**Comment by RedDevel2** [comment]
#183

**Pull request closed without merging**
