### PR TITLE
Update Viaversion for 1.20.2

### PR DESCRIPTION
**Pull request by RedDevel2**

### CODE REVIEW

**Comment by Protonull** [comment]
bump

**Comment by RedDevel2** [comment]
Decided it's not worth the trouble to figure out what's wrong. Since we're already working on updating to 1.20 now.
Besides people can already connect with 1.20.1, for which all the mods are available atm.

**Comment by Huskydog9988** [comment]
Can you describe the issue? Also, mc is up to `1.20.4`, so viaversion may still be necessary unless they are targeting that version.

**Comment by RedDevel2** [comment]
We're targeting latest mc version.
Bug is that it just didn't allow you to connect with any version anymore. Perhaps something to do with dependencies.

**Comment by Huskydog9988** [comment]
Maybe, my initial impression of the issue without more info would either be a config issue, or maybe some edge case in the plugin itself. Because viaversion is running in two places, that might have something to do with it, but it *should* work despite it.

**Pull request closed without merging**
